# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Signal-StackTrace
version:      0.04
version_from: ./lib/Signal/StackTrace.pm
installdirs:  site
requires:
    blib:                          0
    Carp:                          0
    Config:                        0
    Data::Dumper:                  0
    strict:                        0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
